version: '3'

services:
  farcry2:
    build: .
    restart: always
    ports:
     - "9000:9000/tcp"
     - "9000-9003:9000-9003/udp"
    volumes:
     - ./data:/farcry2
    environment:
     - PUID=1000
     - PGID=133
