version: '3'

services:
  farcry2:
    build: .
    restart: always
    ports:
     - "9000-9003:9000-9003/udp"
     - "9000-9003:9000-9003/tcp"
    volumes:
     - ./data:/farcry2
    environment:
     - PUID=1001
     - PGID=1001
